"""
PRISMA Review Agent — Pydantic AI Systematic Literature Review.

A standalone, agent-based systematic review tool following PRISMA 2020.
"""

from prisma_review_agent.models import (
    Article,
    EvidenceSpan,
    ReviewProtocol,
    PRISMAFlowCounts,
    PRISMAReviewResult,
    RoBTool,
    RoBJudgment,
    GRADECertainty,
    SearchStrategy,
    ScreeningBatchResult,
    RiskOfBiasResult,
    StudyDataExtraction,
    GRADEAssessment,
    ReviewPlan,
    PlanRejectedError,
    MaxIterationsReachedError,
    DataChartingRubric,
    PRISMANarrativeRow,
    CriticalAppraisalRubric,
    GroundingValidationResult,
    GroundingVerdict,
    ClaimType,
    AtomicClaim,
    PrismaReview,
    Abstract,
    Introduction,
    Methods,
    Results,
    Discussion,
    Conclusion,
    Theme,
    ExtractedStudy,
    ThematicSynthesisResult,
    PrismaFlow,
    OutputFormat,
    BiasAssessment,
    QuantitativeAnalysis,
    SECTION_FORMAT,
    BUILTIN_SECTIONS,
    RubricSectionOutput,
    RubricSectionConfig,
    StudyDataExtractionReport,
    # Feature 006
    FieldDefinition,
    ChartingSection,
    ChartingTemplate,
    FieldAnswer,
    SectionExtractionResult,
    AppraisalItemSpec,
    AppraisalDomainSpec,
    CriticalAppraisalConfig,
    ItemRating,
    DomainAppraisal,
    CriticalAppraisalResult,
    # Feature 007
    FieldAgreement,
    SynthesisDivergence,
    ModelReviewRun,
    MergedReviewResult,
    CompareReviewResult,
)
from prisma_review_agent.pipeline import PRISMAReviewPipeline
from prisma_review_agent.agents import default_charting_template, default_appraisal_config
from prisma_review_agent.export import (
    to_markdown, to_json, to_bibtex, to_turtle, to_jsonld,
    to_rubric_markdown, to_rubric_json,
    # Feature 006
    to_charting_markdown, to_charting_json,
    to_appraisal_markdown, to_appraisal_json,
    # Feature 007
    to_compare_markdown, to_compare_json,
    to_compare_charting_markdown, to_compare_charting_json,
    # Narrative summary
    to_narrative_summary_markdown, to_narrative_summary_json,
)

__version__ = "0.2.0"

__all__ = [
    "Article",
    "EvidenceSpan",
    "ReviewProtocol",
    "PRISMAFlowCounts",
    "PRISMAReviewResult",
    "PRISMAReviewPipeline",
    "RoBTool",
    "RoBJudgment",
    "GRADECertainty",
    "SearchStrategy",
    "ScreeningBatchResult",
    "RiskOfBiasResult",
    "StudyDataExtraction",
    "GRADEAssessment",
    "ReviewPlan",
    "PlanRejectedError",
    "MaxIterationsReachedError",
    "DataChartingRubric",
    "PRISMANarrativeRow",
    "CriticalAppraisalRubric",
    "GroundingValidationResult",
    "GroundingVerdict",
    "ClaimType",
    "AtomicClaim",
    "to_markdown",
    "to_json",
    "to_bibtex",
    "to_turtle",
    "to_jsonld",
    "PrismaReview",
    "Abstract",
    "Introduction",
    "Methods",
    "Results",
    "Discussion",
    "Conclusion",
    "Theme",
    "ExtractedStudy",
    "ThematicSynthesisResult",
    "PrismaFlow",
    "OutputFormat",
    "BiasAssessment",
    "QuantitativeAnalysis",
    "SECTION_FORMAT",
    "BUILTIN_SECTIONS",
    "RubricSectionOutput",
    "RubricSectionConfig",
    "StudyDataExtractionReport",
    "to_rubric_markdown",
    "to_rubric_json",
    # Feature 006
    "FieldDefinition",
    "ChartingSection",
    "ChartingTemplate",
    "FieldAnswer",
    "SectionExtractionResult",
    "AppraisalItemSpec",
    "AppraisalDomainSpec",
    "CriticalAppraisalConfig",
    "ItemRating",
    "DomainAppraisal",
    "CriticalAppraisalResult",
    "default_charting_template",
    "default_appraisal_config",
    "to_charting_markdown",
    "to_charting_json",
    "to_appraisal_markdown",
    "to_appraisal_json",
    # Feature 007
    "FieldAgreement",
    "SynthesisDivergence",
    "ModelReviewRun",
    "MergedReviewResult",
    "CompareReviewResult",
    "to_compare_markdown",
    "to_compare_json",
    "to_compare_charting_markdown",
    "to_compare_charting_json",
    "to_narrative_summary_markdown",
    "to_narrative_summary_json",
]
