"""
PRISMA Review Agent — Pydantic AI Systematic Literature Review.

A standalone, agent-based systematic review tool following PRISMA 2020.
"""

from prisma_review_agent.models import (
    Article,
    EvidenceSpan,
    ReviewProtocol,
    PRISMAFlowCounts,
    PRISMAReviewResult,
    RoBTool,
    RoBJudgment,
    GRADECertainty,
    SearchStrategy,
    ScreeningBatchResult,
    RiskOfBiasResult,
    StudyDataExtraction,
    GRADEAssessment,
    ReviewPlan,
    PlanRejectedError,
    MaxIterationsReachedError,
    DataChartingRubric,
    PRISMANarrativeRow,
    CriticalAppraisalRubric,
    GroundingValidationResult,
    GroundingVerdict,
    ClaimType,
    AtomicClaim,
    PrismaReview,
    Abstract,
    Introduction,
    Methods,
    Results,
    Discussion,
    Conclusion,
    Theme,
    ExtractedStudy,
    ThematicSynthesisResult,
    PrismaFlow,
    OutputFormat,
    BiasAssessment,
    QuantitativeAnalysis,
)
from prisma_review_agent.pipeline import PRISMAReviewPipeline
from prisma_review_agent.export import to_markdown, to_json, to_bibtex, to_turtle, to_jsonld

__version__ = "0.2.0"

__all__ = [
    "Article",
    "EvidenceSpan",
    "ReviewProtocol",
    "PRISMAFlowCounts",
    "PRISMAReviewResult",
    "PRISMAReviewPipeline",
    "RoBTool",
    "RoBJudgment",
    "GRADECertainty",
    "SearchStrategy",
    "ScreeningBatchResult",
    "RiskOfBiasResult",
    "StudyDataExtraction",
    "GRADEAssessment",
    "ReviewPlan",
    "PlanRejectedError",
    "MaxIterationsReachedError",
    "DataChartingRubric",
    "PRISMANarrativeRow",
    "CriticalAppraisalRubric",
    "GroundingValidationResult",
    "GroundingVerdict",
    "ClaimType",
    "AtomicClaim",
    "to_markdown",
    "to_json",
    "to_bibtex",
    "to_turtle",
    "to_jsonld",
    "PrismaReview",
    "Abstract",
    "Introduction",
    "Methods",
    "Results",
    "Discussion",
    "Conclusion",
    "Theme",
    "ExtractedStudy",
    "ThematicSynthesisResult",
    "PrismaFlow",
    "OutputFormat",
    "BiasAssessment",
    "QuantitativeAnalysis",
]
